version: "1.0"

services:
  postgres:
    image: 'postgres:16.1-alpine3.19'
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=anomes
      - POSTGRES_PASSWORD=local