services:
  server_db:
    image: postgres:16.1-alpine3.19
    container_name: server_db
    expose:
      - 5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=anonmes
      - POSTGRES_PASSWORD=local
    command: -p 5433

  server:
    container_name: server
    build:
      context: ./messenger
      dockerfile: backend.Dockerfile
    ports:
      - 8081:8080
    environment:
      DATASOURCE_URL: jdbc:postgresql://server_db:5433/anonmes
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: local

      KEYCLOAK_CLIENT_ID: anonmes
      KEYCLOAK_SECRET: jikvp5fJQE7yOl6723o2ewb9PYIXDDbK
      JWT_SECRET: askfj-dskfSJ23-SSADSXX_d34032et3453-XX44S

      APP_SECRET: local

  client:
    container_name: client
    build:
      context: ./next_chat
      dockerfile: client.Dockerfile
    ports:
      - 3000:3000
    environment:
      GOOGLE_CLIENT_ID: 634385362994-230hbtkhlepi0qrpjdscsq1jbe6e1rmh.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: 232390jakpffnldhi3nvPAnrbuidda0334h04-3234324
      JWT_SECRET: askfj-dskfSJ23-SSADSXX_d34032et3453-XX44S
      KEYCLOAK_CLIENT_ID: anonmes
      KEYCLOAK_SECRET: jikvp5fJQE7yOl6723o2ewb9PYIXDDbK

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    volumes:
      - ./keycloak_imports/realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - 8888:8888
      - 8443:8443
    environment:
      JWT_SECRET: askfj-dskfSJ23-SSADSXX_d34032et3453-XX44S

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5434/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      keycloak.url: http://keycloak:8888
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8888
      HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY: none
      KC_PROXY_ADDRESS_FORWARDING: true

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [start-dev, --http-port=8888, --import-realm]

    restart: always
    depends_on:
      - keycloak_db

  keycloak_db:
    image: postgres:16.1-alpine3.19
    container_name: keycloak_db
    expose:
      - 5434
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=password
    command: -p 5434