version: "1.0"

services:
  postgres:
    image: 'postgres:16.1-alpine3.19'
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=anonmes
      - POSTGRES_PASSWORD=local
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      DATASOURCE_URL: "jdbc:postgresql://postgres:5432/anonmes"
      DATASOURCE_USERNAME: "postgres"
      DATASOURCE_PASSWORD: "local"
